"""
Django settings for petracker project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv(override=False)
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-local-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'pe-tracker-web-production.up.railway.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'petracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'petracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


_db_password = (
    os.environ.get('SUPABASE_DB_PASSWORD') or
    os.environ.get('DB_PASSWORD') or
    os.environ.get('DATABASE_PASSWORD') or
    os.environ.get('POSTGRES_PASSWORD') or
    ''
)

_db_url = (
    os.environ.get('DATABASE_URL') or
    f'postgresql://postgres.dvtkpsqcwfekntaslwwn:{_db_password}'
    f'@aws-1-eu-west-2.pooler.supabase.com:6543/postgres'
    f'?sslmode=require'
)
_db_config = dj_database_url.parse(_db_url, conn_max_age=0, ssl_require=False)
_db_config.setdefault('OPTIONS', {}).update({
    'gssencmode': 'disable',
    'channel_binding': 'disable',
})
DATABASES = {'default': _db_config}

import sys
_all_env_keys = [k for k in os.environ if any(x in k.upper() for x in ('DB', 'DATABASE', 'SUPABASE', 'POSTGRES', 'PASSWORD', 'SECRET', 'RAILWAY'))]
print(f"[STARTUP] relevant_env_keys={sorted(_all_env_keys)}", file=sys.stderr, flush=True)
print(f"[STARTUP] DATABASE_URL set={bool(os.environ.get('DATABASE_URL'))} "
      f"SUPABASE_PW_len={len(os.environ.get('SUPABASE_DB_PASSWORD',''))} "
      f"parsed_pw_len={len(_db_config.get('PASSWORD') or '')}",
      file=sys.stderr, flush=True)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
CSRF_TRUSTED_ORIGINS = ['https://pe-tracker-web-production.up.railway.app']